### ISSUE TITLE
SpinTools IDE gives: "env: node: No such file or directory" error with  external tool "pnut_ts" on MacOS

### ISSUE THREAD

**Issue by dgately** [maccasoft/spin-tools#12]
"env: node: No such file or directory" error is displayed with  external tool "pnut_ts" on MacOS. And, no compile is executed.

System Info: SpinTools IDE on MacBook Pro Apple Silicon M2 w/MacOS (15.1.1). The pnut_ts external tool is version 1.43.2, Build date: 9/22/2024, GitHub: https://github.com/ironsheep/PNut-TS

External Tool Settings:
```
Name: pnut_ts
Program: /Users/altergator/Documents/pnut_ts/pnut_ts
Arguments: ${file}
```
RESULT:
```
/Users/altergator/Documents/pnut_ts/pnut_ts debug_text.spin2
env: node: No such file or directory
```
Note: The same program & arguments data compiles successfully on the Command line in Terminal (see attached image).

![SpinToolsIDE-Tools-Issue2](https://github.com/user-attachments/assets/6ec15399-5d01-4735-aa1a-2fd230aa71b7)

**Comment by dgately** [comment]
Note: Node.js v18.12.1 is installed on this MacBook Pro

**Comment by maccasoft** [comment]
Seems that pnut_ts doesn't start in the correct directory (shoud be the same directory where the editor file is saved).
Try to change the file argument to "${file.loc}/${file}" this should give the full path name to the file.

**Comment by dgately** [comment]
I've tried the suggestion of using ${file.loc}/${file} but no success. It just prints the following in the Console:

`pnut_ts /Users/altergator/flexprop/samples/debug/debug_text.spin2 -d
`
But no binary file is created (even using '-o debug_text.binary')...

I've also moved a copy of pnut_ts into the same directory as the .spin2 to see if it would execute correctly.
And, tried setting "./pnut_ts" as the program to see if it run as in a Terminal.

I copied all of these examples from the failed attempts in SpinTools IDE's console to the Terminal and they succeed to compile that way.

Note: Just for 'fun' I tried some simple command-line commands within a tool (Program: 'mv', Arguments: '${file.name}.bin  ${file.name}.binary') and it actually does change the name of the compiled .bin to .binary! So, why wouldn't any other valid program & argumants not execute?

And  another (Program: 'echo', Arguments: "HELP!") and it responded correctly:
```
echo HELP!
HELP!
```

**Comment by maccasoft** [comment]
> I've tried the suggestion of using ${file.loc}/${file} but no success. It just prints the following in the Console:
> 
> `pnut_ts /Users/altergator/flexprop/samples/debug/debug_text.spin2 -d ` But no binary file is created (even using '-o debug_text.binary')...

That seems another problem, I see that there isn't the path to pnut_ts (like in your first post), is pnut_ts in your path ?
Unfortunately if the executable is not found the console output doesn't display an error, and based on what you see, seems that pnut_ts doesn't run at all.

If I'm not wrong, the correct settings for you should be:

```
Name: pnut_ts
Program: /Users/altergator/Documents/pnut_ts/pnut_ts
Arguments: ${file.loc}/${file}

```

**Comment by dgately** [comment]
> Name: pnut_ts
> Program: /Users/altergator/Documents/pnut_ts/pnut_ts
> Arguments: ${file.loc}/${file}

I should have mentioned that I had already tired exactly that... Same result!

**Comment by maccasoft** [comment]
Well, I guess this is some weird behaviour of the MacOS, I don't own a Mac so I can't test it, I suggest you to post the question on the Parallax forum and see if other Mac users have some suggestions.
In the meantime I'll fix the code to display an error message if the external program can't run for some reasons.
