### ISSUE TITLE
invalid jmp address calculated in repeat blocks with debug statements

### ISSUE THREAD

**Issue by DarkInsanePyro** [maccasoft/spin-tools#5]
### Issue
While shoving debug statements everywhere troubleshooting my code, I found an anomaly that was introduced. The REPEAT block is getting an incorrect return jump address when a debug statement is present. It can be done with the most basic of code snippets, see below.

I haven't done extensive testing or digging to see if this is impacted elsewhere. A brief `repeat [var] from [min] to [max]` operation didn't have the issue though.

### Versions
Not present with 0.27.0.
Present (issue) with 0.28.0 and 0.28.1.

### Scenario
**Code:**
```Spin2
CON
    _CLKFREQ = 160_000_000

PUB Start()
    repeat
        debug("Test")
        waitms(1000)
```

**Expected Outcome**
"Test" printed over and over indefinitely.

**Actual Outcome**
"Test" printed once.

### Compiled in 0.27.2 (works):
```
' Object header (var size 4)
01490 00000       08 00 00 80    Method Start @ $00008 (0 parameters, 0 returns)
01494 00004       14 00 00 00    End
' PUB Start()
01498 00008       00             (stack size)
'     repeat
'         debug("Test")
01499 00009       43 00 01       DEBUG #1
'         waitms(1000)
0149C 0000C       46 E8 03       CONSTANT (1000)
0149F 0000F       19 80          WAITMS
014A1 00011       12 77          JMP $00009 (-9)
014A3 00013       04             RETURN
' Debug data
00B24 00000       0C 00         
00B26 00002       04 00         
00B28 00004       04 06 54 65 73
00B2D 00009       74 00 00
```

### Compiled in 0.28.0 - 0.28.1 (doesn't work):
```
' Object header (var size 4)
01490 00000       08 00 00 80    Method Start @ $00008 (0 parameters, 0 returns)
01494 00004       14 00 00 00    End
' PUB Start()
01498 00008       00             (stack size)
'     repeat
'         debug("Test")
01499 00009       43 00 01       DEBUG #1
'         waitms(1000)
0149C 0000C       46 E8 03       CONSTANT (1000)
0149F 0000F       19 80          WAITMS
014A1 00011       12 79          JMP $00009 (-7)
014A3 00013       04             RETURN
' Debug data
00B24 00000       0C 00         
00B26 00002       04 00         
00B28 00004       04 06 54 65 73
00B2D 00009       74 00 00
```

**Comment by maccasoft** [comment]
Missed the debug bytecode size, this was altering all relative jumps.
Fixed in 320a276d658897a577afdef7ffc3457ef2d01731
