### ISSUE TITLE
Indentation Lines misalignment

### ISSUE THREAD

**Issue by jrullan** [maccasoft/spin-tools#7]
![image](https://github.com/maccasoft/spin-tools/assets/6475312/c530f286-f162-48e5-8d0f-820b1d099e75)

I have set my tab stops to 2, 4, 6, 8, ... etc.

**Comment by maccasoft** [comment]
Seems the drawing is off by two lines.
Can you attach a text file to test ?

**Comment by maccasoft** [comment]
Reproduced on Windows only, where line ending is a CR/LF pair, by adding a blank line to a block comment, the code was not counting the line ending pair correctly.

Fixed with commit 02be5e4f1ffad9666c001934ac58cd79ba5a2fe6
