### ISSUE TITLE
Spin Tools IDE v0.35.0 does not exec successfully on Apple Silicon MacBook Pro

### ISSUE THREAD

**Issue by dgately** [maccasoft/spin-tools#9]
Both versions (spin-tools-0.35.0-macosx-aarch64-jre.tar.gz AND spin-tools-0.35.0-macosx-aarch64.tar.gz) of the Spin Tools IDE release 0.35.0 will not run on MacBook Pro (Apple Silicon, OS: Sonoma, 14.4.1, aarch64).

**Note: Release 0.34.2 does not have this issue.**

After unpacking the tar.gz of the jre release and opening the Spin Tools IDE, the following is received:

**non-JRE release:**
The non-jre release just displays the app's icon in the Dock for a moment then disappears.

**JRE release:**
![JRE result](https://github.com/maccasoft/spin-tools/assets/3009364/f6b5b717-3e6e-4d9c-8902-316081fa8b95)

**Notes:**

To diagnose a bit...

1. I tried launching the jre release from the command-line and got the same results as above (the dialog pops-up)
2. I tried launching the non-jre release from the command-line:
```
% ./JavaAppLauncher 
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-cocoa-4964r8 in java.library.path: /Users/altergator/Downloads/Spin Tools IDE.app/Contents/MacOS
	no swt-cocoa in java.library.path: /Users/altergator/Downloads/Spin Tools IDE.app/Contents/MacOS
	no swt in java.library.path: /Users/altergator/Downloads/Spin Tools IDE.app/Contents/MacOS
	Can't load library: /Users/altergator/.swt/lib/macosx/x86_64/libswt-cocoa-4964r8.jnilib
	Can't load library: /Users/altergator/.swt/lib/macosx/x86_64/libswt-cocoa.jnilib
	Can't load library: /Users/altergator/.swt/lib/macosx/x86_64/libswt.jnilib
	Can't load library: /Users/altergator/.swt/lib/macosx/x86_64/libswt-cocoa-4964r8.jnilib

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:345)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:254)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:110)
	at com.maccasoft.propeller.SpinTools.<clinit>(SpinTools.java:3238)
```

**Comment by maccasoft** [comment]
Try to delete the folder /Users/altergator/.swt it holds the binary libraries and should be recreated at the start of the application and populated with the correct libraries.
If still doesn't work, please post the content list of that folder (and subfolders).

**Comment by dgately** [comment]
**With the non-jre release, running Spin Tools IDE v0.35.0 leaves only an x86_64 set of libs in .swt:**

> `% ls -lR .swt                                                                          
> 
> total 0
> drwxr-xr-x@ 3 altergator  staff  96 May  2 09:13 lib
> 
> 
> .swt/lib:
> total 0
> drwxr-xr-x@ 3 altergator  staff  96 May  2 09:13 macosx
> 
> .swt/lib/macosx:
> total 0
> drwxr-xr-x@ 3 altergator  staff  96 May  2 09:13 x86_64
> 
> .swt/lib/macosx/x86_64:
> total 1128
> -rwxr-xr-x@ 1 altergator  staff  576624 May  2 09:13 libswt-cocoa-4964r8.jnilib`

**With the jre release, running Spin Tools IDE just puts up the "Unable to load Java Runtime" dialog and does NOT create a .swt directory...**

**The former .swt directory from Spin Tools IDE v0.34.2 has the following content:**

> `% ls -lR swt
> total 0
> drwxr-xr-x  3 altergator  staff  96 Jul 20  2018 lib
> 
> swt/lib:
> total 0
> drwxr-xr-x  4 altergator  staff  128 Jul 12  2023 macosx
> 
> swt/lib/macosx:
> total 0
> drwxr-xr-x@  4 altergator  staff  128 Jul 12  2023 aarch64
> drwxr-xr-x  17 altergator  staff  544 May  1 09:00 x86_64
> 
> swt/lib/macosx/aarch64:
> total 1720
> -rwxr-xr-x@ 1 altergator  staff  594448 Jul 12  2023 libswt-cocoa-4956r13.jnilib
> -rwxr-xr-x@ 1 altergator  staff  282176 Jul 12  2023 libswt-pi-cocoa-4956r13.jnilib
> 
> swt/lib/macosx/x86_64:
> total 11584
> -rwxr-xr-x  1 altergator  staff  306392 Jul 20  2018 libswt-cocoa-4623.jnilib
> -rwxr-xr-x  1 altergator  staff  342740 Jan 21  2020 libswt-cocoa-4716.jnilib
> -rwxr-xr-x  1 altergator  staff  555760 Mar  4  2022 libswt-cocoa-4934r6.jnilib
> -rwxr-xr-x  1 altergator  staff  555760 Nov 29  2020 libswt-cocoa-4936r26.jnilib
> -rwxr--r--@ 1 altergator  staff  597680 Jan  5  2023 libswt-cocoa-4956r13.jnilib
> -rwxr-xr-x  1 altergator  staff  513152 Mar 27  2023 libswt-cocoa-4958r2.jnilib
> -rwxr-xr-x@ 1 altergator  staff  514256 Sep 25  2023 libswt-cocoa-4962r3.jnilib
> -rwxr-xr-x@ 1 altergator  staff  576624 May  1 08:50 libswt-cocoa-4964r8.jnilib
> -rwxr-xr-x  1 altergator  staff  287632 Jul 20  2018 libswt-pi-cocoa-4623.jnilib
> -rwxr-xr-x  1 altergator  staff  355204 Jan 21  2020 libswt-pi-cocoa-4716.jnilib
> -rwxr-xr-x  1 altergator  staff  266944 Mar  4  2022 libswt-pi-cocoa-4934r6.jnilib
> -rwxr-xr-x  1 altergator  staff  266944 Nov 29  2020 libswt-pi-cocoa-4936r26.jnilib
> -rwxr--r--@ 1 altergator  staff  283904 Jan  5  2023 libswt-pi-cocoa-4956r13.jnilib
> -rwxr-xr-x  1 altergator  staff  284016 Mar 27  2023 libswt-pi-cocoa-4958r2.jnilib
> -rwxr-xr-x@ 1 altergator  staff  284016 Sep 25  2023 libswt-pi-cocoa-4962r3.jnilib
> altergator ~ % 
> `
>

**Comment by maccasoft** [comment]
It is a bit confusing, seems that the native libraries are extracted to the x86_64 folder instead of, what I suppose, the aarch64 folder. I'm a bit clueless about this, I don't know if the libraries are extracted to the wrong directory because of an issue in the new swt jar package, or something else.

I think that the x86_64 package should work on both architectures, try that package (delete again the .swt folder before so there aren't library conflicts).

**Comment by dgately** [comment]
Success with both the x86_64 JRE and non-JRE releases of 0.36.0! You can close, but it's odd that the aarch64 release has this issue.

**Comment by dgately** [comment]
Closing, as of the success in the last comment
